#!/usr/bin/env python
print('Qual eh o seu nome?')
nome = input()
print('Prazer, %s' %nome)
print('Qual eh a sua idade?')
idade = input()
print('Muito obrigado, sua idade eh: ' + str(idade))
print('Qual eh o seu sexo?')
sexo = input()
print('Obrigado pela resposta, registrei que voce eh do sexo %s' %sexo)
print('Qual eh a cidade que voce mora?')
cidade = input()
print('Legal! Voce mora em ' +str(cidade)+'!')
print('Em que Estado fica %s?' %cidade)
estado = input()
print('Show! Nao sabia que ' +str(cidade)+ ' ficava em '+str(estado))
print('Qual eh o seu estado civil?')
estadoCivil = input()
print('Muito obrigado, seu estado civil eh: ' + str(estadoCivil))
